[TRICK]由于git commit 返回非零，所以屏蔽之

diff --git a/hooks/post-commit b/hooks/post-commit
--- a/hooks/post-commit
+++ b/hooks/post-commit
@@ -70,13 +70,13 @@ cd "${private_prj_name}"
 git commit -m "$commit_msg"
 ret=$?
 cd -
-if [ $ret -ne 0 ]; then
-    log_error "${LINENO}:  failed : $ret.EXIT"
-	cd "${private_prj_name}"
-    git reset --hard
-	ret=$?
-    exit 1
-fi 
+#if [ $ret -ne 0 ]; then
+#    log_error "${LINENO}:  failed : $ret.EXIT"
+#	cd "${private_prj_name}"
+#    git reset --hard
+#	ret=$?
+#    exit 1
+#fi 
 
 cd "${POST_COMMIT_STACK_ABS_DIR}"
 cached_prj_name=".${prj_name}.cached"
@@ -85,13 +85,13 @@ log_info "${LINENO}: git commit ${cached_prj_name}..."
 git commit -m "$commit_msg"
 ret=$?
 cd -
-if [ $ret -ne 0 ]; then
-    log_error "${LINENO}:  failed : $ret.EXIT"
-	cd "${private_prj_name}"
-    git reset --hard
-	ret=$?
-    exit 1
-fi 
+#if [ $ret -ne 0 ]; then
+#    log_error "${LINENO}:  failed : $ret.EXIT"
+#	cd "${private_prj_name}"
+#    git reset --hard
+#	ret=$?
+#    exit 1
+#fi 
 cd "${POST_COMMIT_STACK_ABS_DIR}"
 
 exit 0
